import { Footer } from "@/components/footer";
import { Navbar } from "../components/navbar";
import "./globals.css";

// Define un array de links
const linksArray = [
  { id: "1", title: "Inicio", url: "/" },
  { id: "2", title: "Emcolmed", url: "/about-us" },
  { id: "3", title: "Productos", url: "/products" },
  { id: "4", title: "Contáctanos", url: "#contact-us" },
];

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar links={linksArray} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
